CREATE OR REPLACE FUNCTION fn_abono_cuenta(
	p_ctaeq numeric,
	p_imp numeric,
	p_mon integer,
	p_user character varying)
    RETURNS TABLE(codret integer, mensaje text) 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
DECLARE
    V_EMP   INTEGER := 1;
    V_CTA   INTEGER := 0;
    V_OPE   INTEGER := 0;
    V_MOD   INTEGER := 0;
    V_TOP   INTEGER := 0;
    V_SBO   INTEGER := 0;

    V_NREL  INTEGER := 0;
    V_STAT  INTEGER := 9;
BEGIN
    -- BUSCA LLAVE CUENTA
    SELECT STEMP, ST111CTA, ST111OPER, ST111MOD, ST111TOPE, ST111SBOP
    INTO V_EMP, V_CTA, V_OPE, V_MOD, V_TOP, V_SBO
    FROM MST111
    WHERE ST111CTAEQ = p_ctaeq;

    -- OBTIENE NUMERO RELACION
		SELECT COALESCE(MAX(STNREL) + 1, 1)
		INTO V_NREL
		FROM MST015
		WHERE STEMP = V_EMP AND STMOD = 50 AND STTRAN = 1;
		-- CREA CABECERA CONTABLE
		INSERT INTO MST015 (stemp, stmod, sttran, stnrel, st15fech, st15user, st15estd)
		VALUES (V_EMP, 50, 1, V_NREL, CURRENT_DATE, p_user, 'N');
	
		-- VALIDA SI LA CUENTA EXISTE
		IF V_CTA IS NULL OR V_CTA = 0 THEN
			-- INDICA ERROR POR QUE CUENTA NO EXISTE
			UPDATE MST015 SET st15estd = 'E'
			WHERE STEMP = V_EMP AND STMOD = 50 AND STTRAN = 1 AND STNREL = V_NREL;
			RETURN QUERY SELECT 99, 'CUENTA NO EXISTE';
		END IF;
		
	-- CREA ASIENTO CONTABLE SOBRE CUENTA
		INSERT INTO MST016 (stemp, stmod, sttran, stnrel, STFECH, stord, stsbord, st16imp, ST16DBHB, st16cta, st16oper, st16fech, st16user)
		VALUES (V_EMP, 50, 1, V_NREL, CURRENT_DATE, 100, 1, 0, 1, V_CTA, V_OPE, CURRENT_DATE, p_user);

	-- VALIDA ESTADO DE LA CUENTA
		SELECT STESTD INTO V_STAT FROM MST011
		WHERE STEMP = V_EMP AND STCTA = V_CTA AND STOPER = V_OPE AND STMOD = V_MOD AND STTOPE = V_TOP AND STSBOP = V_SBO ;
		-- VALIDA EL ESTADO DE LA CUENTA
		IF V_STAT IS NULL OR V_STAT = 9 THEN
			-- INDICA ERROR POR QUE LA CUENTA ESTA INHABILITADA
			UPDATE MST015 SET st15estd = 'E'
			WHERE STEMP = V_EMP AND STMOD = 50 AND STTRAN = 1 AND STNREL = V_NREL;
			RETURN QUERY SELECT 0, 'CUENTA NO ESTA ACTIVA';
		END IF;
	-- CREA ASIENTO CONTABLE SOBRE ESTADO DE LA CUENTA
		INSERT INTO MST016 (stemp, stmod, sttran, stnrel, STFECH, stord, stsbord, st16imp, ST16DBHB, st16cta, st16oper, st16fech, st16user)
		VALUES (V_EMP, 50, 1, V_NREL, CURRENT_DATE, 100, 2, 0, 1, V_CTA, V_OPE, CURRENT_DATE, p_user);

	-- INGRESA EL SALDO EN LA CUENTA
		UPDATE MST011 SET STSDO = STSDO + p_imp
		WHERE STEMP = V_EMP AND STCTA = V_CTA AND STOPER = V_OPE AND STMOD = V_MOD AND STTOPE = V_TOP AND STSBOP = V_SBO AND STMDA = P_MON;
	-- CREA ASIENTO CONTABLE SOBRE EL SALDO
		INSERT INTO MST016 (stemp, stmod, sttran, stnrel, STFECH, stord, stsbord, st16imp, ST16DBHB, st16cta, st16oper, st16fech, st16user)
		VALUES (V_EMP, 50, 1, V_NREL, CURRENT_DATE, 100, 3, p_imp, 2, V_CTA, V_OPE, CURRENT_DATE, p_user);
	
	-- CONTABILIZA TRANSACCION
		UPDATE MST015 SET st15estd = 'S'
		WHERE STEMP = V_EMP AND STMOD = 50 AND STTRAN = 1 AND STNREL = V_NREL;

    RETURN QUERY SELECT 0, 'ABONO CON EXITO';

EXCEPTION
    WHEN OTHERS THEN
	-- CAPTURA ERROR DENTRO DE LA TRANSACCION
        BEGIN
		-- SI EXISTE CABECERA
            UPDATE MST015 SET st15estd = 'E'
            WHERE STEMP = V_EMP AND STMOD = 50 AND STTRAN = 1 AND STNREL = V_NREL;
		-- SI NO EXISTE CABECERA
            INSERT INTO MST015 (stemp, stmod, sttran, stnrel, st15fech, st15user, st15estd)
            VALUES (V_EMP, 50, 1, V_NREL, CURRENT_DATE, p_user, 'E');
        EXCEPTION WHEN OTHERS THEN
            NULL;
        END;
        RETURN QUERY SELECT 99, 'ERROR EN ABONO';
END;
$BODY$;