CREATE OR REPLACE PROCEDURE sp_desembolso(
	IN p_ncta integer,
	IN p_mda integer,
	IN p_user text,
	IN p_imp numeric,
	IN p_tas numeric,
	IN p_pla numeric)
LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
	V_EMP	NUMERIC:= 1;
	V_TASM	NUMERIC(10,6);
	V_VAR1	NUMERIC(10,6);
	V_CUO	NUMERIC(15,2);
	i		INTEGER;
	
	V_INTMES	NUMERIC(15,2);
	V_CAPMES	NUMERIC(15,2);
	V_SDOPEN	NUMERIC(15,2);
	V_SDOTOT	NUMERIC(15,2);

	V_TDOC	NUMERIC(2);	
	V_NDOC	VARCHAR(12);

	
	V_OPE	NUMERIC(9);
	V_MOD	NUMERIC(3);
	V_TOP	NUMERIC(3);
	V_SBO	NUMERIC(3);

	V_CTAEQ	NUMERIC;
	V_CODRE	NUMERIC;
	V_MENSA	VARCHAR;
BEGIN
	-- VALIDAMOS SI ES NATURAL O JURIDICA
	SELECT STTDOC, STNDOC INTO V_TDOC, V_NDOC FROM MST8
	WHERE STEMP = V_EMP AND STNCTA = P_NCTA;

    -- Asignar número de operación
    SELECT COALESCE(MAX(STOPER) + 1, 250225)
    INTO V_OPE
    FROM MST011;
	
	IF V_TDOC = 1 THEN
		V_MOD:= 30;
		V_TOP:= 0;
		V_SBO:= 0;
	ELSIF V_TDOC = 2 THEN
		V_MOD:= 92;
		V_TOP:= 0;
		V_SBO:= 0;
	END IF;

	-- CREA CREDITO CON SALDO CERO
	INSERT INTO MST011 (STEMP, STCTA, STOPER, STMDA, STMOD, STTOPE, STSBOP, STFCRE, STSDO, STESTD, STUSER)
	VALUES (V_EMP, P_NCTA, V_OPE, P_MDA, V_MOD, V_TOP, V_SBO, CURRENT_DATE, 0, 0, P_USER);
	V_TASM:= (P_TAS/100/12);						-- OBTIENE TASA MENSUAL
	V_VAR1 := power(1 + V_TASM, P_PLA);						-- VARIABALE 1
	V_CUO := P_IMP * ((V_TASM*V_vAR1)/(V_VAR1-1));	-- VALOR CUOTA MENSUAL

	-- CREAMOS CRONOGRAMA
	V_SDOPEN:= P_IMP;
	V_SDOTOT:= 0;
	FOR i IN 1..P_PLA LOOP
		IF I < P_PLA THEN
			V_INTMES:= V_SDOPEN * V_TASM;
			V_CAPMES:= V_CUO - V_INTMES;

			INSERT INTO MST601 (STEMP,STMOD,STCTA,STOPER,STTOPE,STSBOP,STMDA,STNRO,ST61IMP1,ST61IMP2,ST61ESTD,ST61FECH,ST61USER)
			VALUES (V_EMP,V_MOD, P_NCTA, V_OPE, V_TOP, V_SBO, P_MDA,i, V_CAPMES, V_INTMES, '', CURRENT_DATE, P_USER);
			V_SDOPEN:= V_SDOPEN - V_CAPMES;
			V_SDOTOT:= V_SDOTOT + V_CAPMES;
		ELSE
			V_INTMES:= 0;
			V_CAPMES:= V_SDOPEN;
			INSERT INTO MST601
				(STEMP,STMOD,STCTA,STOPER,STTOPE,STSBOP,STMDA,STNRO,ST61IMP1,ST61IMP2,ST61ESTD,ST61FECH,ST61USER)
			VALUES (V_EMP, V_MOD, P_NCTA, V_OPE, V_TOP, V_SBO, P_MDA,i, V_CAPMES, V_INTMES, '', CURRENT_DATE, P_USER);
			V_SDOPEN:= V_SDOPEN - V_CAPMES;
			V_SDOTOT:= V_SDOTOT + V_CAPMES;
		END IF;
	END LOOP;

	-- ACTUALIZA CREDITO
	UPDATE MST011 SET STSDO = -V_SDOTOT
	WHERE STEMP = V_EMP AND STCTA = P_NCTA AND STOPER = V_OPE AND STMDA = P_MDA AND STMOD = V_MOD AND STTOPE = V_TOP AND STSBOP = V_SBO;

	INSERT INTO MST602 (STEMP, STMOD, STCTA, STOPER, STTOPE, STSBOP, STMDA, ST62TAS1, ST62TAS2, ST62FECH, ST62USER)
	VALUES (V_EMP,V_MOD,P_NCTA,V_OPE,V_TOP,V_SBO,P_MDA,P_TAS,V_TASM,CURRENT_DATE,P_USER);

	SELECT ST111CTAEQ INTO V_CTAEQ FROM MST111
	WHERE STEMP = V_EMP AND ST111CTA = P_NCTA;

	IF V_CTAEQ IS NULL OR V_CTAEQ = 0 THEN 
		-- CORRECCIÓN 1: La función retorna TABLE, no SELECT... INTO simple
		SELECT * INTO rec_crear_cuenta 
		FROM FN_CREAR_CUENTA(
		    p_tdoc  => V_TDOC,
		    p_ndoc  => V_NDOC,
		    p_mod   => 21,
		    p_tope  => 0,
		    p_sbop  => 0,
		    p_mda   => 0,
		    p_user  => P_USER
		);
		
		-- Asignar valores de retorno
		V_CTAEQ := rec_crear_cuenta.v_ctaeq;
		V_CODRE := rec_crear_cuenta.v_codret;
		V_MENSA := rec_crear_cuenta.v_mensaje;
		
		-- Verificar si la creación fue exitosa
		IF V_CODRE != 0 THEN
			RAISE EXCEPTION 'Error al crear cuenta equivalente: %', V_MENSA;
		END IF;
	END IF;

	PERFORM FN_ABONO_CUENTA(
        p_ctaeq => V_CTAEQ,  
        p_imp   => P_IMP,      
        p_mon   => P_MDA,
        p_user  => P_USER
    );
	
EXCEPTION 
    WHEN OTHERS THEN
		IF EXISTS (
			SELECT 1 FROM MST011
			WHERE STEMP = V_EMP AND STCTA = P_NCTA AND STOPER = V_OPE AND STMDA = P_MDA AND STMOD = V_MOD AND STTOPE = V_TOP AND STSBOP = V_SBO
		) THEN
			DELETE FROM MST011
			WHERE STEMP = V_EMP AND STCTA = P_NCTA AND STOPER = V_OPE AND STMDA = P_MDA AND STMOD = V_MOD AND STTOPE = V_TOP AND STSBOP = V_SBO;
		END IF;
		RAISE EXCEPTION 'Error capturado: %', SQLERRM;
END;
$BODY$;